steps:
- task: UseNode@1
  displayName: âš™ï¸ Use Node 16.x
  inputs:
    version: 16.x

- task: YarnInstaller@3
  displayName: âš™ï¸ Use yarn 1.x
  inputs:
    versionSpec: 1.x

- task: Yarn@3
  displayName: âš™ï¸ yarn install
  inputs:
    projectDirectory: src/nerdbank-streams

- task: Yarn@3
  displayName: ğŸ› ï¸ yarn build
  inputs:
    projectDirectory: src/nerdbank-streams
    arguments: build

- task: Yarn@3
  displayName: ğŸ§ª yarn test
  inputs:
    projectDirectory: src/nerdbank-streams
    arguments: test

- task: Yarn@3
  displayName: ğŸ§ª yarn tslint
  inputs:
    projectDirectory: src/nerdbank-streams
    arguments: tslint --project .
